### ISSUE TITLE
How to use plugins with default values

### ISSUE THREAD

**Issue by TimPietrusky** [sinnerschrader/dekk#20]
## Issue description
What is the desired way to use all plugins with their default values? Because doing it like this

```html
<Deck>
    <Plugins>
    </Plugins>
</Deck>
```

is throwing an error:

```
index.js:260 Uncaught TypeError: Cannot read property 'type' of undefined
    at index.js:260
    at Array.map (<anonymous>)
```

## Steps to reproduce
* Add the `Plugins` component without any elements to the `Deck`

## Versions
1. yarn: 1.3.2
2. node: 6.9.1
3. dekk: 1.0.0-5

**Comment by pixelass** [comment]
I fixed this in the new version. (wait for 1.0.0-6)

```jsx
<Plugins/>
```

will not do anything but it will not throw an error. (Same goes for `Elements`)
