### ISSUE TITLE
Documentation is importing the "Config"

### ISSUE THREAD

**Issue by TimPietrusky** [sinnerschrader/dekk#21]
## Issue description
The documentation for `Plugins` is still importing the `Config` component instead of the `Plugins`.

## Steps to reproduce
* [Adding URLs](https://sinnerschrader.github.io/dekk/api/manual/plugins.html#adding-urls)
* [Enable Paging](https://sinnerschrader.github.io/dekk/api/manual/plugins.html#enable-paging)

## Versions
1. yarn: 1.3.2
2. node 6.9.1
3. dekk: 1.0.0-5

**Comment by pixelass** [comment]
thx .. will fix along the way.
