### ISSUE TITLE
Documentation is missing animation, animationIn & animationOut

### ISSUE THREAD

**Issue by TimPietrusky** [sinnerschrader/dekk#30]
## Issue description
There is no documentation on how the properties `animation`, `animationIn` and `animationOut` can be used and on which elements. 

## Steps to reproduce
* Open the [animations](https://sinnerschrader.github.io/dekk/api/manual/animations.html) documentation
* Search for "animation" or "animationIn" or "animationOut"

## Versions
dekk: 1.0.0.-17

**Comment by pixelass** [comment]
This is part of `Slide`. It seems that this page is missing in general.

I'll add that, thx.

**Comment by pixelass** [comment]
The docs have been updated: 
https://sinnerschrader.github.io/dekk/api/manual/slides.html
