### ISSUE TITLE
Master slide "Big" with only one area A

### ISSUE THREAD

**Issue by TimPietrusky** [sinnerschrader/dekk#33]
## Issue description
Right now we only `Cover` and `Chapter`. Both of them are dividing the screen into A and B. 

It would be nice to have an element that is in center of the whole screen. And that in only one area A. 

This way the `Cover` would be different from the `Chapter` and people can use it in different ways. 

### Big

| Slot | Content        | Alignment      |
|------|----------------|----------------|
| A    | Any    | center, bottom |

```
┏━━━━━━━━━━━━━━━┓
┃               ┃
┃       A       ┃
┃               ┃
┗━━━━━━━━━━━━━━━┛
```

## Versions
3. dekk: 1.0.0-17

**Comment by pixelass** [comment]
Sometimes the things you suggest make sense... sometimes

**Comment by TimPietrusky** [comment]
This is the biggest blocker right now when using Dekk 😱
