### ISSUE TITLE
How to use "Code"

### ISSUE THREAD

**Issue by TimPietrusky** [sinnerschrader/dekk#39]
## Issue description
The documentation is missing an example on how `Code` should be used. 

I'm trying it like this, but I only get errors:

```html
      <Code>
        const helloWorld = foo => {
          console.log(foo)
        }
      </Code>
```

or like this:

```html
      <Code>
      {
        const helloWorld = foo => {
          console.log(foo)
        }
      }
      </Code>
```

## Steps to reproduce
* Open [Code](https://sinnerschrader.github.io/dekk/api/manual/text-elements.html#code) documentation

## Versions
3. dekk: 1.0.0-17

**Comment by pixelass** [comment]
The documentation simply links to https://github.com/conorhastings/react-syntax-highlighter.

The code has to be a string

```jsx
<Code>
  {`
    const helloWorld = foo => {
      console.log(foo)
    }
  `}
</Code>
```


```jsx
const code = `
  const helloWorld = foo => {
    console.log(foo)
  }
`
<Code>
  {code}
</Code>
```

**Comment by TimPietrusky** [comment]
Thank you! Would love to see this as part of the official documentation.
