### ISSUE TITLE
"Text" inside "Main" master slide not working

### ISSUE THREAD

**Issue by TimPietrusky** [sinnerschrader/dekk#50]
## Issue description
When using the `Text` component in the `Main` master slide I get this error:

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

## Steps to reproduce
* Use the `Main` master slide
* Add the `Text` element like this:
```
    <A>
      <Text>This is some text</Text>
    </A>
```

## Versions
1. yarn: 1.5.1
2. node 6.9.1
3. dekk: 1.0.0

**Comment by pixelass** [comment]
Can you paste a link to the original code or paste a snippet?

It might be that you mixed default with named exports

```jsx
import Text from '@dekk/text'
// But 
import {Title} from '@dekk/text'
```

**Comment by pixelass** [comment]
I just tested it. please see my previous comment. It's probably something similar.
