### ISSUE TITLE
Config component is required

### ISSUE THREAD

**Issue by TimPietrusky** [sinnerschrader/dekk#9]
## Issue description
Without having the config component loaded, dekk will fail with the following message:
```
Uncaught TypeError: Cannot read property 'paging' of undefined
    at Deck.get (index.js:286)
```

## Steps to reproduce
* Use the gh-pages example

## Steps to fix
* Load the Config component
* Add the Config component into Deck component

## Versions
dekk 1.0.0-4

1. yarn: 1.3.2
2. node 6.9.1

**Comment by pixelass** [comment]
This issue will be closed by #12
